/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'

export const CosmicWidget = ({ ...props }) => {
  // function to animate the widget by rotating the group

  const group = useRef()
  const group1 = useRef()
  // animate the whole group to rotate  around the y axis
 useFrame(() => {
    group.current.rotation.y += 0.01
    group1.current.rotation.x += 0.01

  })
  const { nodes, materials } = useGLTF('/cosmic_widget.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        ref={group1}
        geometry={nodes.r326662.geometry}
        material={nodes.r326662.material}
        position={[-0.15, 1.61, -0.43]}
        rotation={[-1.91, -0.06, 1.1]}
        scale={[2.46, 2.46, 2.46]}
      />
      <mesh
        geometry={nodes.r326663.geometry}
        material={nodes.r326663.material}
        position={[-0.15, 1.61, -0.43]}
        rotation={[-1.91, -0.06, 1.1]}
        scale={[2.46, 2.46, 2.46]}
      />
      <mesh
        geometry={nodes.r326666.geometry}
        material={nodes.r326666.material}
        position={[-0.15, 1.61, -0.43]}
        rotation={[-1.91, -0.06, 1.1]}
        scale={[2.79, 2.79, 2.79]}
      />
      <mesh
        geometry={nodes.r326667.geometry}
        material={nodes.r326667.material}
        position={[-0.15, 1.61, -0.43]}
        rotation={[-1.91, -0.06, 1.1]}
        scale={[2.79, 2.79, 2.79]}
      />
      <mesh
        geometry={nodes.r326668.geometry}
        material={nodes.r326668.material}
        position={[-0.15, 1.61, -0.43]}
        rotation={[-1.91, -0.06, 1.1]}
        scale={[2.79, 2.79, 2.79]}
      />
      <mesh
        geometry={nodes.s326676.geometry}
        material={nodes.s326676.material}
        position={[-0.12, 2, -0.58]}
        rotation={[1.98, -0.43, 2.21]}
        scale={[3.47, 3.47, 3.47]}
      />
      <mesh
        geometry={nodes.s326677.geometry}
        material={nodes.s326677.material}
        position={[-0.17, 1.84, -0.95]}
        rotation={[-2.89, -1.24, -2.45]}
        scale={[3.47, 3.47, 3.47]}
      />
      <mesh
        geometry={nodes.s326679.geometry}
        material={nodes.s326679.material}
        position={[-0.09, 1.33, -0.34]}
        rotation={[-2.98, -1.25, -2.53]}
        scale={[3.47, 3.47, 3.47]}
      />
    </group>
  )
}

useGLTF.preload('/cosmic_widget.glb')
