/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 991519166 (https://sketchfab.com/991519166)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/dbb2f075329747a09cc8add2ad05acad
title: Galaxy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Galaxy = ({ ...props }) => {
  const group = useRef()
  const { nodes, materials } = useGLTF("galaxy.glb");
  console.log(nodes)
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Galaxy_Material_#65_0'].geometry} material={materials.Material_65} />
          </group>
          {/* <group name="Sphere001" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Sphere001_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          </group> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/galaxy.glb')
