/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HomoMilch (https://sketchfab.com/homomilk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/d84f98de4a0a4d509d5df6e52936823c
title: Perspective
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Perspective = ({ ...props }) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/perspective.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-62.5, 100, 62.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube009_Material_0.geometry} material={nodes.Cube009_Material_0.material} />
          </group>
          <group position={[-62.5, 100, 62.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cube007_Material_0.geometry} material={nodes.Cube007_Material_0.material} />
          </group>
          <group position={[24.74, 123.59, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.21, 0.21, 0.21]}>
            <mesh geometry={nodes.Cube004_Material_0.geometry} material={nodes.Cube004_Material_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/perspective.glb')
